language: python

env:
  global:
    - EXAHOST="127.0.0.1:8563"

services:
  - docker

install:
    - docker run --detach --name exasoldb  --privileged -p  0.0.0.0:8899:8888  -p 0.0.0.0:6594:6583 --stop-timeout 120  exasol/docker-db:6.1.5-d1
    - wget https://www.exasol.com/support/secure/attachment/79638/EXAplus-6.0.15.tar.gz
    - tar -xvf ./EXAplus-6.0.15.tar.gz
    - sleep 60
#    - docker logs exasoldb
#    - docker exec -it exasoldb dwad_client list  # just for the log
#    - docker inspect exasoldb  # just for the log
    - ls -la
    - ./easyinstall.sh 127.0.0.1:6594 'default/go' "w:$(docker exec  exasoldb cat /exa/etc/EXAConf | grep Write | sed 's/ *WritePasswd *= *//' | base64 --decode)"
    - sleep 60
    - pip install pyexasol

script:
    - python test/basic_test.py