language: python

services:
  - docker

install:
    - docker run --detach --name exasoldb  --privileged -p  0.0.0.0:8899:8888  -p 0.0.0.0:6594:6583 --stop-timeout 120  exasol/docker-db
#    - wget https://www.exasol.com/support/secure/attachment/79638/EXAplus-6.0.15.tar.gz
#    - tar -xvf ./EXAplus-6.0.15.tar.gz
    - sleep 60
#    - docker logs exasoldb
#    - docker exec -it exasoldb dwad_client list  # just for the log
#    - docker inspect exasoldb  # just for the log
    - ls -la
    - ./easyinstall.sh 127.0.0.1:6594 'default/go' "w:$(docker exec  exasoldb cat /exa/etc/EXAConf | grep Write | sed 's/ *WritePasswd *= *//' | base64 --decode)"
    - sleep 120
    - pip install pyexasol
#    - ./EXAplus-6.0.15/exaplus -c 127.0.0.1:8899 -x -u sys -p exasol -q -sql "ALTER SYSTEM SET SCRIPT_LANGUAGES = 'PYTHON=builtin_python R=builtin_r JAVA=builtin_java GO=localzmq+protobuf:///bfsdefault/default/go/GolangImage?#buckets/bfsdefault/default/go/go_entrypoint/go.sh'"

script:
    - python test/test_bigemit.py "localhost:8899"
    - python test/test_bigread.py "localhost:8899"
    - python test/test_datatype.py "localhost:8899"